config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#homepage"

  resources :pages, only: [:homepage]
  resources :dashboards, only: [:new, :create] do
    post "update_order", on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :dashboard_type
  belongs_to :user

  validates :content, presence: true

  before_validation :set_dashboard_index

  scope :by_user,
        -> (user_id) { where(user_id: user_id) }

  class << self
    def update_order(dashboard_order_params)
      dashboard_order_params.each do |id, index|
        dashboard = Dashboard.find_by_id(id)
        next if dashboard.nil?
        dashboard.update_column(:index, index)
      end
    end
  end

  private

    def set_dashboard_index
      self.index = Dashboard.by_user(self.user_id).count + 1
    end
end

app/models/dashboard_type.rb
class DashboardType < ApplicationRecord
  has_many :dashboards

  validates               :title, presence: true
  validates_uniqueness_of :title
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :dashboards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action      :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:update_order]

  def new
    @dashboard = current_user.dashboards.build
  end

  def create
    @dashboard = current_user.dashboards.build(dashboard_params)

    if @dashboard.save
      flash[:success] = "New dashboard successfully created!"
      redirect_to root_path
    else
      flash.now[:error] = "You made some mistakes within creating a dashboard."
      render "new"
    end
  end

  def update_order
    Dashboard.update_order(dashboard_order_params)
  end

  private

    def dashboard_params
      params.require(:dashboard).permit(:content, :dashboard_type_id)
    end

    def dashboard_order_params
      params.require(:dashboards)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
    @dashboards = current_user.dashboards.order("index ASC") if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-danger"
      when :alert then "alert alert-warning"
    end
  end
end

app/views/dashboards/new.html.erb
<h2>New dashboard</h2>

<%= form_for @dashboard do |f| %>
  <div class="form-group">
    <%= f.label :dashboard_type %><br />
    <%= f.select :dashboard_type_id, options_for_select(DashboardType.pluck(:title, :id)), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content %><br />
    <%= f.text_field :content, autofocus: true, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<% if current_user %>
  <ul class="nav justify-content-end">
    <li class="nav-item">
      <%= link_to "New dashboard", new_dashboard_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Homepage", root_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" href="#" tabindex="2" aria-disabled="true"><%= current_user.email %></a>
    </li>
    <li class="nav-item">
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key.to_sym) %>">
          <%= value %>
        </div>
      <% end %>

      <%= render "layouts/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/homepage.html.erb
<% unless current_user %>
  <div class="jumbotron">
    <h1 class="display-4">Welcome to Dashboards!</h1>
    <p class="lead">Start using it by creating an account or sign in</p>
    <hr class="my-4">
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success" %>
    <%= link_to "Sign in", new_user_session_path, class: "btn btn-info" %>
  </div>
<% end %>

<% if @dashboards %>
  <div id="dashboardsList">
    <% @dashboards.each do |dashboard| %>
        <div class="panel panel-default border border-success dashboard" data-id=<%= dashboard.id %>>
          <div class="panel-body text-center"><%= dashboard.content.html_safe %></div>
        </div>
    <% end %>
  </div>
  <div class="buttons text-center">
    <button type="button" class="btn btn-success" id="saveDashboardOrder">Save</button>
  </div>
<% end %>